# Dockerfile para la aplicación PHP
FROM php:8.2-apache

# Copiar el código de la aplicación al directorio del servidor web
WORKDIR /var/www/html
COPY . /var/www/html/
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf
RUN chown -R www-data:www-data /var/www/html \
    && a2enmod rewrite

# Verificar los archivos copiados
RUN ls -la /var/www/html/

# Actualizar la lista de paquetes e instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    make\
    wget \
    unzip \
    git \
    gcc \
    g++ \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

#Extensión de Mysql
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli
# Ejecutar el Makefile
RUN make
# Instalar Composer
RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php \
    && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm /tmp/composer-setup.php \
    && composer --version
# Exponer el puerto 80
EXPOSE 80
