version: '3.8'
services:
  web:
    image: cgarzon49/php-sample-app:v6.0
    env_file:
      - .env
    ports:
      - "8080:80"    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: web
    networks:
      - default

  bd:
    env_file:
      - .env
    image: cgarzon49/php-sample-bd:v2.0
    restart: unless-stopped
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: "5s"
      interval: "10s"
      start_period: "3s"
      retries: 5
    container_name: bd
    networks:
      - default

networks:
  default:
    driver: bridge
